import MapKit
import SwiftUI

public extension MKPointOfInterestCategory {
    var image: Image {
        switch self {
//        case .airport: Image(.airport)
//        case .amusementPark: Image(.amusementPark)
//        case .aquarium: Image(.aquarium)
        case .atm: Image(.atm)
        case .bakery: Image(.bakery)
        case .bank: Image(.bank)
//        case .beach: Image(.beach)
//        case .brewery: Image(.brewery)
        case .cafe: Image(.cafe)
//        case .campground: Image(.campground)
        case .carRental: Image(.carRental)
//        case .evCharger: Image(.evCharger)
        case .fireStation: Image(.fireStation)
        case .fitnessCenter: Image(.fitnessCenter)
        case .foodMarket: Image(.foodMarket)
        case .gasStation: Image(.gasStation)
        case .hospital: Image(.hospital)
        case .hotel: Image(.hotel)
        case .laundry: Image(.laundry)
        case .library: Image(.library)
//        case .marina: Image(.marina)
        case .movieTheater: Image(.movieTheater)
        case .museum: Image(.museum)
//        case .nationalPark: Image(.nationalPark)
//        case .nightlife: Image(.nightlife)
        case .park: Image(.park)
        case .parking: Image(.parking)
        case .pharmacy: Image(.pharmacy)
        case .police: Image(.police)
//        case .postOffice: Image(.postOffice)
        case .publicTransport: Image(.publicTransport)
//        case .rentalCarLocation: Image(.rentalCarLocation)
        case .restaurant: Image(.restaurant)
        case .restroom: Image(.restroom)
        case .school: Image(.school)
//        case .stadium: Image(.stadium)
        case .store: Image(.store)
//        case .theater: Image(.theater)
        case .university: Image(.university)
//        case .winery: Image(.winery)
//        case .zoo: Image(.zoo)
        default: Image(.unknown)
        }
    }
}
